db_05_3/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

db_05_3/movies/urls.py
from django.urls import path
from . import views


app_name = "movies"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/comments/", views.comments_create, name="comments_create"),
    path(
        "<int:movie_pk>/comments/<int:comment_pk>/delete/",
        views.comments_delete,
        name="comments_delete",
    ),
    path("<int:movie_pk>/likes/", views.likes, name="likes"),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
]

db_05_3/project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

db_05_3/movies/models.py
from django.db import models
from django.conf import settings


class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content


class Movie(models.Model):
    hashtags = models.ManyToManyField(Hashtag,blank=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_movies"
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

db_05_3/movies/forms.py
from django import forms
from .models import Movie, Comment


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        # fields = '__all__'
        fields = ('title', 'content',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('movie', 'user',)

db_05_3/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import (
    require_http_methods,
    require_POST,
    require_safe,
)
from django.contrib.auth.decorators import login_required
from .models import Movie, Comment,Hashtag
from .forms import MovieForm, CommentForm


@require_safe
def index(request):
    movies = Movie.objects.order_by("-pk")

    context = {
        "movies": movies,
    }
    return render(request, "movies/index.html", context)


@login_required
@require_http_methods(["GET", "POST"])
def create(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect("movies:detail", movie.pk)
    else:
        form = MovieForm()
    context = {
        "form": form,
    }
    return render(request, "movies/create.html", context)


@require_safe
def detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {
        "movie": movie,
        "comment_form": comment_form,
        "comments": comments,
    }
    return render(request, "movies/detail.html", context)


@require_POST
def delete(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.user.is_authenticated:
        if request.user == movie.user:
            movie.delete()
            return redirect("movies:index")
    return redirect("movies:detail", movie.pk)


@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.user == movie.user:
        if request.method == "POST":
            form = MovieForm(request.POST, instance=movie)
            if form.is_valid():
                form.save()
                return redirect("movies:detail", movie.pk)
        else:
            form = MovieForm(instance=movie)
    else:
        return redirect("movies:index")
    context = {
        "movie": movie,
        "form": form,
    }
    return render(request, "movies/update.html", context)


@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
        return redirect("movies:detail", movie.pk)
    return redirect("accounts:login")


@require_POST
def comments_delete(request, movie_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect("movies:detail", movie_pk)


@require_POST
def likes(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)

        if movie.like_users.filter(pk=request.user.pk).exists():
            # if request.user in movie.like_users.all():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)
        return redirect("movies:index")
    return redirect("accounts:login")

@login_required
def hashtag(request, hash_pk):
    hashtag = get_object_or_404(Hashtag, pk=hash_pk)
    movies = hashtag.movie_set.order_by('-pk')
    context = {
        'hashtag': hashtag, 
        'movies': movies,
    }
    return render(request, 'movies/hashtag.html', context)

db_05_3/movies/templates/movies/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>영화 정보 작성</h1>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="작성" class="btn btn-primary btn-sm">
  </form>
  <a href="{% url 'movies:index' %}" class="btn btn-secondary btn-sm">이전</a>
{% endblock content %}

db_05_3/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h2>영화 정보 상세</h2>
  <hr>
  <h3>{{ movie.pk }} 번째 영화 : {{ movie.title }}</h3>
  <br>
  <p>{{ movie|hashtag_link|safe }}</p>
  <br>
  <p>{{ movie.created_at }} 작성</p>
  <p>{{ movie.updated_at }} 최종 수정</p>
  <hr>
  <div class="d-flex">
    {% if user == movie.user %}
      <a href="{% url 'movies:update' movie.pk %}" class="btn btn-warning btn-sm">영화 정보 수정</a>
      <form action="{% url 'movies:delete' movie.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="영화 정보 삭제" class="btn btn-danger btn-sm">
      </form>
    {% endif %}
    <a href="{% url 'movies:index' %}" class="btn btn-secondary btn-sm">이전</a>
  </div>
  <hr>
  <h4>리뷰 목록</h4>
  {% if comments %}
    <p><b>{{ comments|length }}개의 리뷰가 있습니다.</b></p>
  {% endif %}
  <ul>
    {% for comment in comments %}
      <li>
        {{ comment.user }} - {{ comment.content }}
        {% if user == comment.user %}
          <form action="{% url 'movies:comments_delete' movie.pk comment.pk %}" method="POST" class="d-inline">
            {% csrf_token %}
            <input type="submit" value="삭제" class="btn btn-danger btn-sm">
          </form>
        {% endif %}
      </li>
    {% empty %}
      <li>리뷰가 없어요..!</li>
    {% endfor %}
  </ul>

  <hr>
  {% if request.user.is_authenticated %}
    <form action="{% url 'movies:comments_create' movie.pk %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      <input type="submit" value="작성" class="btn btn-primary btn-sm">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}" class="btn btn-success btn-sm">리뷰를 작성하려면 로그인하세요.</a>
  {% endif %}
{% endblock content %}

db_05_3/movies/templates/movies/hashtag.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h2>{{hashtag.content}}</h2>
  <p>{{movies|length}}개의 게시글</p>
</div>
<hr>
<div>
  <h3>{{hashtag.content}}를 태그한글</h3>
  <br>
  {% for movie in movies  %}
    <h5>영화 {{movie.title}}</h5>
    <p>{{movie.comment_set.all|length}}개의 댓글</p>
    <a href="{% url 'movies:detail' movie.pk %}">상세글로 바로가기</a>
    <hr>  
  {% endfor %}

</div>


{% endblock content %}

db_05_3/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>영화 게시판</h1>
    {% if request.user.is_authenticated %}
      <a href="{% url 'movies:create' %}" class="btn btn-primary btn-sm">영화 정보 작성</a>
    {% else %}
      <a href="{% url 'accounts:login' %}" class="btn btn-success">새 영화 정보를 작성하려면 로그인하세요.</a>
    {% endif %}
  </div>
  <hr>
  {% for movie in movies %}
    <p>{{ movie.pk }}번째 영화</p>
    <h3>{{ movie.title }}</h3>
    <br>
    <p>{{ movie.content }}</p>
    <br>
    <p>
      <a href="{% url 'accounts:profile' movie.user %}">{{ movie.user }}</a>님 작성
    </p>
    <div>
      <form action="{% url 'movies:likes' movie.pk %}" method="post">
        {% csrf_token %}
        {% if user in movie.like_users.all %}
          <input type="submit" value="좋아요 취소" class="btn btn-primary btn-sm">
        {% else %}
          <input type="submit" value="좋아요" class="btn btn-primary btn-sm">
        {% endif %}
      </form>
		  <span>{{ movie.like_users.all|length }} 명이 이 글을 좋아합니다.</span>
    </div>
    <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-warning btn-sm">영화 상세 정보 보기</a>
    <hr>
  {% endfor %}
{% endblock content %}

db_05_3/movies/templates/movies/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="수정" class="btn btn-warning btn-sm">
  </form>
  <hr>
  <a href="{% url 'movies:index' %}" class="btn btn-secondary btn-sm">이전</a>
{% endblock content %}